site_name: abvio
site_url: https://wladerer.github.io/abvio
site_description: A better VASP input file

theme:
  name: 'material'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey 
    accent: blue
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    accent: ablue
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  features:
    - toc.follow

repo_name: wladerer/abvio
repo_url: https://github.com/wladerer/abvio

nav:
- About: index.md
- Quickstart: quickstart.md
- File Format: format.md
- PBS and SLURM: jobs.md


markdown_extensions:
- tables
- admonition
- toc:
    permalink: true
    title: Page contents
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.extra
- pymdownx.arithmatex:
    generic: true

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [.]
        options:
          members_order: source
          separate_signature: true
          filters: ["!^_"]
          docstring_options:
            ignore_init_summary: true
          merge_init_into_class: true
          signature_crossrefs: true
